remote_theme: pages-themes/minimal@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one
title: GIIECEC
description: Grupo Interdisciplinario de Investigación en Educación en Ciencias Experimentales y de la Computación
show_downloads: false
logo: /assets/img/logo.png
